name: website
channels:
  - conda-forge

dependencies:
  - python=3.10
  - mkdocs=1.6.0
  - mkdocs-material=9.5.32
  - pymdown-extensions=10.9
  - fontawesome-markdown=0.2.6
  - pip:
      - poetry-core
